[c]
cmd = "cargo"
aliases = [
    { alias = "b", cmd = "build" },
    { alias = "f", cmd = "fmt" },
    { alias = "r", cmd = "build --release" },
]

[db]
cmd = "yarn"
expand = [{ key = 'db', value = '@monologue/db-client' }]
aliases = [
    { alias = "lm", cmd = "workspace @db list-migrations" },
    { alias = "cm", cmd = "workspace @db create-migrations" },
    { alias = "m", cmd = "workspace @db migrate-prod-dangerous" },
    { alias = "r", cmd = "workspace @db revert-last-prod-migration-dangerous" },
]

[g]
cmd = "git"
aliases = [
    { alias = "c", cmd = "you meant to use gt" },
    { alias = "lol", cmd = "log --pretty=oneline --abbrev-commit --graph --decorate" },
    { alias = "sd", cmd = "stash drop" },
    { alias = "sl", cmd = "stash list" },
    { alias = "sp", cmd = "stash push -u" },
]

[gt]
cmd = "gt"
aliases = [
    { alias = 'a', cmd = 'add' },
    { alias = 'd', cmd = "diff" },
    { alias = 'dc', cmd = "diff --cached" },
    { alias = 'df', cmd = "delete --force" },
    { alias = 'r', cmd = 'restack' },
    { alias = 's', cmd = "submit" },
    { alias = 'sf', cmd = "sync --force" },
    { alias = 'sp', cmd = "split" },
    { alias = 'st', cmd = "status" },
    { alias = 'ws', cmd = "submit --web" },
]

[ms]
cmd = "yarn manage-stg"
expand = [
    { key = 'm', value = '--repoOwner withgraphite --repoName monologue' },
    { key = 'd', value = '--repoOwner withgraphite --repoName david-test-repo' },
]
aliases = [
    { alias = "c", cmd = "console" },
    { alias = "j", cmd = "job" },
    { alias = "m", cmd = "merge" },
    { alias = "o", cmd = "oneoffs" },
    { alias = "u", cmd = "user" },
]

[mp]
cmd = "yarn manage-prod"
expand = [
    { key = 'm', value = '--repoOwner withgraphite --repoName monologue' },
    { key = 'd', value = '--repoOwner withgraphite --repoName david-test-repo' },
]
aliases = [
    { alias = "c", cmd = "console" },
    { alias = "ci", cmd = "ci" },
    { alias = "j", cmd = "job" },
    { alias = "m", cmd = "merge" },
    { alias = "mq", cmd = "mq" },
    { alias = "mwr", cmd = "mwr" },
    { alias = "o", cmd = "oneoffs" },
    { alias = "pr", cmd = "pr" },
    { alias = "r", cmd = "repo" },
    { alias = "u", cmd = "user" },
]

[y]
cmd = "yarn"
expand = [
    { key = 's', value = '@monologue/server' },
    { key = 'db', value = '@monologue/db-client' },
    { key = 'm', value = '@monologue/mergeability' },
]
aliases = [
    { alias = "a", cmd = "app" },
    { alias = "bd", cmd = "buildserverdeps" },
    { alias = "b", cmd = "build" },
    { alias = "b1", cmd = "workspace {0} build" },
    { alias = "i", cmd = "install" },
    { alias = "l", cmd = "lint" },
    { alias = "l1", cmd = "workspace {0} lint" },
    { alias = "sp", cmd = "server" },
    { alias = "ss", cmd = "server-stg" },
]

[t]
cmd = "yarn"
expand = [
    { key = 's', value = '@monologue/server' },
    { key = 'db', value = '@monologue/db-client' },
    { key = 'm', value = '@monologue/mergeability' },
    { key = 'ts', value = '@monologue/ts-helpers' },
    { key = 'c', value = "@monologue/cache-client" },
    { key = 'n', value = "@monologue/notifications" },
    { key = 'cli', value = "@withgraphite/graphite-cli" },
]
aliases = [
    { alias = "1", cmd = "workspace {0} test-one" },
    { alias = "a", cmd = "workspace {0} test" },
]

[v]
cmd = "aws"
aliases = [{ alias = "l", cmd = "sso login" }]
