[a]
cmd = "aws"
aliases = [
    { sub_alias = "ecr-pass", arguments = "ecr get-login-password --region us-west-2" },
    { sub_alias = "l", arguments = "sso login" },
    { sub_alias = "o", arguments = "sso logout" },
]

[c]
cmd = "cargo"
aliases = [
    { sub_alias = "b", arguments = "build" },
    { sub_alias = "f", arguments = "fmt" },
    { sub_alias = "r", arguments = "build --release" },
]

[d]
cmd = "docker"
aliases = [
    { sub_alias = "l", arguments = "login --username AWS --password-stdin 064159781857.dkr.ecr.us-west-2.amazonaws.com" },
]

[db]
cmd = "yarn"
expansions = [{ key = 'db', value = '@monologue/db-client' }]
aliases = [
    { sub_alias = "lm", arguments = "workspace @db list-migrations" },
    { sub_alias = "cm", arguments = "workspace @db create-migrations" },
    { sub_alias = "m", arguments = "workspace @db migrate-prod-dangerous" },
    { sub_alias = "r", arguments = "workspace @db revert-last-prod-migration-dangerous" },
]

[g]
cmd = "git"
aliases = [
    { sub_alias = "c", arguments = "you meant to use gt" },
    { sub_alias = "lol", arguments = "log --pretty=oneline --abbrev-commit --graph --decorate" },
    { sub_alias = "rs", arguments = "restore --staged" },
    { sub_alias = "sd", arguments = "stash drop" },
    { sub_alias = "sl", arguments = "stash list" },
    { sub_alias = "sp", arguments = "stash push -u" },
]

[gt]
cmd = "gt"
aliases = [
    { sub_alias = 'a', arguments = 'add' },
    { sub_alias = 'd', arguments = "diff" },
    { sub_alias = 'dc', arguments = "diff --cached" },
    { sub_alias = 'df', arguments = "delete --force" },
    { sub_alias = 'r', arguments = 'restack' },
    { sub_alias = 's', arguments = "submit" },
    { sub_alias = 'sf', arguments = "sync --force" },
    { sub_alias = 'sp', arguments = "split" },
    { sub_alias = 'st', arguments = "status" },
    { sub_alias = 'ws', arguments = "submit --web" },
]

[ms]
cmd = "yarn manage-stg"
expansions = [
    { key = 'd', value = '--repoOwner withgraphite --repoName david-test-repo' },
    { key = 'j', value = '--repoOwner withgraphite --repoName jess-repo-testing' },
    { key = 'm', value = '--repoOwner withgraphite --repoName monologue' },
]
aliases = [
    { sub_alias = "c", arguments = "console" },
    { sub_alias = "j", arguments = "job" },
    { sub_alias = "m", arguments = "merge" },
    { sub_alias = "o", arguments = "oneoffs" },
    { sub_alias = "u", arguments = "user" },
]

[mp]
cmd = "yarn manage-prod"
expansions = [
    { key = 'm', value = '--repoOwner withgraphite --repoName monologue' },
    { key = 'j', value = '--repoOwner withgraphite --repoName jess-repo-testing' },
    { key = 'd', value = '--repoOwner withgraphite --repoName david-test-repo' },
]
aliases = [
    { sub_alias = "c", arguments = "console" },
    { sub_alias = "ci", arguments = "ci" },
    { sub_alias = "j", arguments = "job" },
    { sub_alias = "m", arguments = "merge" },
    { sub_alias = "mq", arguments = "mq" },
    { sub_alias = "mwr", arguments = "mwr" },
    { sub_alias = "o", arguments = "oneoffs" },
    { sub_alias = "pr", arguments = "pr" },
    { sub_alias = "r", arguments = "repo" },
    { sub_alias = "u", arguments = "user" },
]

[y]
cmd = "yarn"
expansions = [
    { key = 'a', value = '@monologue/graphite-app' },
    { key = "cli", value = "@withgraphite/graphite-cli" },
    { key = 's', value = '@monologue/server' },
    { key = 'db', value = '@monologue/db-client' },
    { key = 'm', value = '@monologue/mergeability' },
    { key = 'git', value = '@monologue/git-client' },
    { key = 'infra', value = '@monologue/infra' },
]
aliases = [
    { sub_alias = "a", arguments = "app" },
    { sub_alias = "bd", arguments = "buildserverdeps" },
    { sub_alias = "b", arguments = "build" },
    { sub_alias = "b1", arguments = "workspace {0} build" },
    { sub_alias = "fe", arguments = "app frontend-only" },
    { sub_alias = "i", arguments = "install" },
    { sub_alias = "l", arguments = "lint" },
    { sub_alias = "lf", arguments = "lint -- --fix" },
    { sub_alias = "l1", arguments = "workspace {0} lint" },
    { sub_alias = "sp", arguments = "server" },
    { sub_alias = "ss", arguments = "server-stg" },
]

[t]
cmd = "yarn"
expansions = [
    { key = 'a', value = "@monologue/graphite-app" },
    { key = 'ai', value = "@monologue/ai-client" },
    { key = 'c', value = "@monologue/cache-client" },
    { key = 'cli', value = "@withgraphite/graphite-cli" },
    { key = 'db', value = '@monologue/db-client' },
    { key = 'git', value = '@monologue/git-client' },
    { key = 'ga', value = "@monologue/parse-gitattributes" },
    { key = 'gco', value = '@monologue/parse-github-codeowners' },
    { key = 'm', value = '@monologue/mergeability' },
    { key = 'n', value = "@monologue/notifications" },
    { key = 's', value = '@monologue/server' },
    { key = 's3', value = '@monologue/s3-client' },
    { key = 'shared', value = '@monologue/shared-types' },
    { key = 'splog', value = '@monologue/splog' },
    { key = 'ts', value = '@monologue/ts-helpers' },
]
aliases = [
    { sub_alias = "1", arguments = "workspace {0} test-one" },
    { sub_alias = "a", arguments = "workspace {0} test" },
]

[w]
cmd = "wezterm"
aliases = [
  { sub_alias = "t", arguments = "cli set-tab-title" },
]
