#!/usr/bin/env bash

install_file() {
  local source=$1
  local target=$2

  local target_file="$HOME/$target"
  local target_dir=$(dirname "$target_file")

  if [ ! -e "$target_file" ]; then
    if [ ! -e "$target_dir" ]; then
        mkdir -p "$target_dir"
    fi
    ln -s `pwd`/$source $target_file
  else
    echo "Skipping $target, file already exists"
  fi
}

install_file "gitconfig" ".gitconfig"
install_file "gitignore" ".gitignore"
install_file "tmux.conf" ".tmux.conf"
install_file "inputrc" ".inputrc"
install_file "zshrc" ".zshrc"
install_file "zsh_custom" ".zsh_custom"
install_file "starship.toml" ".config/starship.toml"
install_file "alacritty.yml" ".config/alacritty/alacritty.yml"
install_file "gtk.css" ".config/gtk-3.0/gtk.css"
install_file "ipython_config.py" ".ipython/profile_default/ipython_config.py"

